ALTER TYPE "VideoProvider" ADD VALUE 'CLOUDINARY';
ALTER TABLE "Video"
ADD COLUMN "videoPublicId" TEXT,
ADD COLUMN "width" INTEGER,
ADD COLUMN "height" INTEGER,
ADD COLUMN "duration" DOUBLE PRECISION;
